# tests/test_secret_key_preservation.py
"""Regression: setup must NEVER regenerate an existing DB_SECRET_KEY.

If DB_SECRET_KEY is regenerated, every stored broker credential becomes
permanently undecryptable and reads as "invalid" in the UI. This caused a loop
where users re-entered broker keys on every restart. The fix: when a key already
exists, /api/setup/complete leaves .env completely untouched.
"""
from unittest.mock import patch


def test_setup_does_not_regenerate_existing_db_secret_key(tmp_path, monkeypatch):
    """When DB_SECRET_KEY already exists in .env, setup must preserve it byte-for-byte."""
    from cryptography.fernet import Fernet

    # A pre-existing .env with a real Fernet key + an unrelated line we expect kept.
    original_key = Fernet.generate_key().decode()
    env_path = tmp_path / ".env"
    env_path.write_text(
        f"DB_SECRET_KEY={original_key}\n"
        f"SOME_OTHER_SETTING=keepme\n"
    )

    import server.main as main
    # Point the app's BASE_DIR-derived .env at our temp file.
    monkeypatch.setattr(main, "BASE_DIR", tmp_path)
    # The DANGEROUS path: the key exists on disk in .env but is NOT in os.environ
    # at the moment setup runs (e.g. .env wasn't reloaded). The code must still find
    # it via _read_env_key and refuse to regenerate. If it only checked os.environ,
    # it would generate a NEW key here and orphan every encrypted credential.
    monkeypatch.delenv("DB_SECRET_KEY", raising=False)

    import server.db as db_mod
    monkeypatch.setattr(db_mod, "DB_PATH", tmp_path / "setup.db")

    payload = {
        "broker": "alpaca",
        "api_key": "TESTKEY1234567890",
        "api_secret": "TESTSECRET1234567890123456789012",
        "account_type": "paper",
        "starter_strategy": "SMA Cross",
        "password": "hunter22",
    }

    # setup_complete() guards on auth.setup_complete(); simulate "not yet complete".
    with patch("server.auth.password_is_set", return_value=False), \
         patch("server.auth.setup_complete", return_value=False):
        with patch("server.engine.start"), patch("server.engine.shutdown"):
            from fastapi.testclient import TestClient
            with TestClient(main.app, raise_server_exceptions=True) as tc:
                r = tc.post("/api/setup/complete", json=payload)

    assert r.status_code == 200, f"setup failed: {r.text}"

    # The KEY must be unchanged...
    env_after = env_path.read_text()
    assert f"DB_SECRET_KEY={original_key}" in env_after, (
        "DB_SECRET_KEY was changed/regenerated by setup — this orphans all "
        "encrypted broker credentials."
    )
    # ...and the unrelated line preserved.
    assert "SOME_OTHER_SETTING=keepme" in env_after
    # And only ONE DB_SECRET_KEY line should exist (no duplicate appended).
    assert env_after.count("DB_SECRET_KEY=") == 1
