"""License key generation and verification for TradeBot.

Asymmetric (Ed25519): the OWNER instance signs keys with a private key
(env TRADEBOT_LICENSE_PRIVATE_KEY); every build verifies with a public key
baked in as LICENSE_PUBLIC_KEY (overridable via env TRADEBOT_LICENSE_PUBLIC_KEY).
A buyer build has only the public key: it can verify but cannot mint.
"""
import base64
import hashlib
import json
import os
import platform
import time
import uuid

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

MACHINE_ANY = "ANY"

# Public verification key (base64 of the 32-byte raw Ed25519 public key).
# Generated by scripts/gen_license_keys.py and pasted here. The matching private
# key lives ONLY on the owner instance, never in source. Overridable via env for
# testing/rotation. Empty by default until the owner runs the generator.
LICENSE_PUBLIC_KEY = ""

# In-process cache: once valid, skip re-verification for 1 hour
_cache: dict = {}
_CACHE_TTL = 3600  # seconds


class LicenseError(Exception):
    pass


def get_machine_id() -> str:
    raw = f"{platform.node()}|{uuid.getnode()}|{platform.machine()}"
    return hashlib.sha256(raw.encode()).hexdigest()


def _load_private_key() -> Ed25519PrivateKey:
    raw_b64 = os.environ.get("TRADEBOT_LICENSE_PRIVATE_KEY", "").strip()
    if not raw_b64:
        raise RuntimeError(
            "TRADEBOT_LICENSE_PRIVATE_KEY is not set. Minting requires the owner "
            "private key. Generate one with: python scripts/gen_license_keys.py"
        )
    try:
        return Ed25519PrivateKey.from_private_bytes(base64.b64decode(raw_b64))
    except Exception as e:
        raise RuntimeError(f"TRADEBOT_LICENSE_PRIVATE_KEY is invalid: {e}")


def _load_public_key() -> Ed25519PublicKey:
    raw_b64 = (os.environ.get("TRADEBOT_LICENSE_PUBLIC_KEY", "").strip()
               or LICENSE_PUBLIC_KEY.strip())
    if not raw_b64:
        raise LicenseError("invalid: verifier not configured")
    try:
        return Ed25519PublicKey.from_public_bytes(base64.b64decode(raw_b64))
    except Exception:
        raise LicenseError("invalid: verifier not configured")


def mint_key(machine_id: str, days: int) -> str:
    """Sign a license key with the owner private key. Raises RuntimeError on buyer builds."""
    priv = _load_private_key()
    expiry = int(time.time()) + days * 86400
    payload = json.dumps({"m": machine_id, "exp": expiry}, separators=(",", ":"))
    sig = priv.sign(payload.encode())
    bundle = json.dumps(
        {"p": payload, "s": base64.b64encode(sig).decode()},
        separators=(",", ":"),
    )
    return base64.urlsafe_b64encode(bundle.encode()).decode()


def verify_key(key: str, machine_id: str | None = None) -> dict:
    """Verify a license key with the public key, then check expiry and machine binding."""
    pub = _load_public_key()
    try:
        bundle = json.loads(base64.urlsafe_b64decode(key.encode()))
        payload_str = bundle["p"]
        sig = base64.b64decode(bundle["s"])
    except Exception:
        raise LicenseError("invalid: key is malformed")

    try:
        pub.verify(sig, payload_str.encode())
    except InvalidSignature:
        raise LicenseError("invalid: signature mismatch")

    payload = json.loads(payload_str)
    now = int(time.time())

    if payload["exp"] < now:
        raise LicenseError("expired: license key has expired")

    if payload["m"] != MACHINE_ANY:
        actual = machine_id or get_machine_id()
        if payload["m"] != actual:
            raise LicenseError("machine: key is locked to a different machine")

    days_remaining = max(0, (payload["exp"] - now) // 86400)
    return {"valid": True, "days_remaining": days_remaining, "machine_id": payload["m"]}


def check_stored_license() -> dict:
    """Verify the stored license key. Result is cached for 1 hour to avoid per-request overhead."""
    global _cache
    now = time.time()

    # Return cached result if still fresh
    if _cache.get("valid") and now < _cache.get("expires_at", 0):
        return {k: v for k, v in _cache.items() if k != "expires_at"}

    from .db import get_app_config
    key = get_app_config("license_key", "")
    if not key:
        result = {"valid": False, "reason": "No license key entered.", "days_remaining": 0}
        _cache = {}
        return result

    try:
        result = verify_key(key)
        result["reason"] = ""
        # Cache valid result for 1 hour
        _cache = {**result, "expires_at": now + _CACHE_TTL}
        return result
    except (LicenseError, RuntimeError) as e:
        _cache = {}
        return {"valid": False, "reason": str(e), "days_remaining": 0}


def invalidate_cache() -> None:
    """Call after storing a new license key so the next request re-verifies."""
    global _cache
    _cache = {}
